name: create docker image on push or pull request
on: [push, pull_request]
jobs:
  publish-docker-develop-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: api
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the fhirpath validation Docker image
        run: |
          LABEL=latest
          docker build api --tag ghcr.io/swisstph/questionnaire_fhirpath_validator:${LABEL}
          docker push ghcr.io/swisstph/questionnaire_fhirpath_validator:${LABEL}
